# -*- coding: utf-8 -*-
{
    'name': 'VBS Sản xuất',
    'version': '19.0.2.5.0',
    'category': 'VBS',
    'summary': 'Lệnh sản xuất, công đoạn, vận chuyển, lịch sản xuất',
    'description': 'Module trung tâm VBS: quản lý đồ may, công đoạn sản xuất, vận chuyển LCH/LX, tích hợp planning + sale.',
    'depends': [
        'vbs_base',
        'vbs_fabric',
        'vbs_config',
        'vbs_planning',
        'sale',
        'mail',
        'hr',
        'base_automation',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/vbs_sequence_data.xml',
        'data/mail_activity_type_data.xml',
        'data/ir_cron.xml',
        'wizard/vbs_garment_cancel_wizard_views.xml',
        'views/vbs_garment_views.xml',
        'views/planning_slot_ext_views.xml',
        'views/sale_order_views.xml',
        'views/vbs_pattern_ext_views.xml',
        'views/vbs_fabric_ext_views.xml',
        'views/vbs_garment_menus.xml',
        'views/vbs_hide_menus.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
