# -*- coding: utf-8 -*-
{
    'name': 'VBS ERP',
    'version': '1.0',
    'category': 'VBS',
    'summary': 'Quản lý đơn hàng may đo VBS',
    'author': 'VBS',
    'depends': [
        'sale',
        'mail',
        'hr',
        'base_automation',
        'vbs_planning',
    ],
    'data': [
        'security/res_groups.xml',
        'security/ir.model.access.csv',
        'security/ir_rules.xml',
        'data/vbs_sequence_data.xml',
        'data/mail_activity_type_data.xml',
        'data/ir_cron.xml',
        'data/vbs_stage_template_data.xml',
        'views/vbs_stage_template_views.xml',
        'views/vbs_pattern_views.xml',
        'views/vbs_pricing_views.xml',
        'views/vbs_sla_config_views.xml',
        'views/vbs_garment_views.xml',
        'views/vbs_fabric_type_views.xml',
        'views/vbs_fabric_order_views.xml',
        'views/vbs_fabric_stock_views.xml',
        'views/vbs_contact_log_views.xml',
        'views/planning_slot_ext_views.xml',
        'views/sale_order_views.xml',
        'views/vbs_menus.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
